# Generated by Django 5.2.4 on 2025-09-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_student'),
    ]

    operations = [
    ]
